name: websocket_sample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  socket_io_client: ^1.0.2
  laravel_echo: ^1.0.0-beta.1
  logger: ^2.0.1
  import_sorter: ^4.6.0
  http: ^1.1.0
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
